# Generated by Django 4.1.2 on 2022-10-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('quantity', models.FloatField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='selling_price',
            new_name='old_price',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='no_of_buyers',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Fake_order_sold',
            field=models.IntegerField(blank=True, default=212312),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='google_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price_list',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='PurchaseModel',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.productmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.purchasestatusmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Productapp.categorymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.ManyToManyField(to='Productapp.imagemodel'),
        ),
    ]
