# Generated by Django 4.1.2 on 2022-10-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0004_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
