# Generated by Django 4.1.2 on 2022-10-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0005_contactmodel_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='delhivery_charge',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
