# Generated by Django 4.1.2 on 2022-10-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0006_productmodel_delhivery_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='delhivery_charge',
            new_name='delivery_charge',
        ),
    ]
