# Generated by Django 4.1.2 on 2022-10-12 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0008_alter_categorymodel_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingordermodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.citymodel'),
        ),
    ]
