# Generated by Django 4.1.2 on 2022-10-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0010_productmodel_is_discount_discountmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='Title',
            new_name='title',
        ),
    ]
