# Generated by Django 4.1.2 on 2022-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0011_rename_title_productmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='delivery_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
