# Generated by Django 4.1.2 on 2022-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0012_alter_productmodel_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
