# Generated by Django 4.1.2 on 2022-10-21 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0015_ordermodel_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
        migrations.CreateModel(
            name='productorderedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productapp.ordermodel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.productmodel')),
            ],
        ),
    ]
