# Generated by Django 4.1.2 on 2022-10-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0016_remove_ordermodel_product_remove_ordermodel_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingordermodel',
            name='product',
        ),
        migrations.CreateModel(
            name='MissingorderedproductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('missorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productapp.missingordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.productmodel')),
            ],
        ),
    ]
