# Generated by Django 4.1.2 on 2022-10-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0017_remove_missingordermodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderedmodel',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
