# Generated by Django 4.1.2 on 2022-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0018_productorderedmodel_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='total_price',
            new_name='delivery_charge',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
