# Generated by Django 4.1.2 on 2022-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0019_rename_total_price_ordermodel_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
