# Generated by Django 4.1.2 on 2022-10-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0020_alter_discountmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasestatusmodel',
            name='color',
            field=models.CharField(default='white', max_length=100),
        ),
    ]
