# Generated by Django 4.1.2 on 2023-02-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0023_productmodel_quanity_text_productmodel_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingorderedproductmodel',
            name='missorder_id',
        ),
        migrations.RemoveField(
            model_name='missingorderedproductmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorderedmodel',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='productorderedmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='missingordermodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.productmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Productapp.productmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DiscountModel',
        ),
        migrations.DeleteModel(
            name='MissingorderedproductModel',
        ),
        migrations.DeleteModel(
            name='productorderedModel',
        ),
    ]
