# Generated by Django 4.1.2 on 2023-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0024_remove_missingorderedproductmodel_missorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='vat',
            field=models.BooleanField(default=True),
        ),
    ]
