# Generated by Django 4.1.2 on 2023-03-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0025_productmodel_vat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='subtotal_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='missingordermodel',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingordermodel',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='missorder_status',
            field=models.BooleanField(default=False),
        ),
    ]
