# Generated by Django 4.1.2 on 2023-03-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0028_missingordermodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
